apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    app: nginx
spec:
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        nginx-enable: "true"
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
