apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workshops.kairen.io
spec:
  group: kairen.io
  version: v1alpha1
  names:
    kind: WorkShop
    plural: workshops
    singular: workshop
    shortNames:
    - ws
  scope: Namespaced
